name: C CI

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Java
    - uses: actions/setup-java@v5
    
    - name: Test
    - run: java Sistema.java